require "prototypes.utils"
require "prototypes.groups"
require "prototypes.tiles"
require "prototypes.buffs"
require "prototypes.technologies"
require "prototypes.projectiles"

require "prototypes.plants.utils"
require "prototypes.plants.rockmalt"
require "prototypes.plants.redbloom"
require "prototypes.plants.nyxoleum"
require "prototypes.plants.mangroove"

require "prototypes.machines.oven"
require "prototypes.machines.research-center"
require "prototypes.machines.deep-fryer"
require "prototypes.machines.trader-t1"

require "prototypes.items.crops"
require "prototypes.items.machines"
require "prototypes.items.materials"
require "prototypes.items.fluids"
require "prototypes.items.foods"
require "prototypes.items.environment-data"

require "prototypes.recipes.recipe-categories"
require "prototypes.recipes.trading"
require "prototypes.recipes.cooking"
require "prototypes.recipes.process-crops"
require "prototypes.recipes.chemicals"
require "prototypes.recipes.materials"
require "prototypes.recipes.research-data"

require "prototypes.planet.noise-expressions.utils"
require "prototypes.planet.noise-expressions.aux"
require "prototypes.planet.noise-expressions.elevation"
require "prototypes.planet.noise-expressions.temperature"
require "prototypes.planet.noise-expressions.moisture"
require "prototypes.planet.noise-expressions.rockpools"
require "prototypes.planet.noise-expressions.plants"
require "prototypes.planet.noise-expressions.starting"
require "prototypes.planet.noise-expressions.decoratives"

require "prototypes.planet.tiles"
require "prototypes.planet.controls"
require "prototypes.planet.planet"