require "prototypes.utils"
require "prototypes.groups"
require "prototypes.tiles"
require "prototypes.buffs"
require "prototypes.technologies"

require "prototypes.entities.plants"
require "prototypes.entities.machines"

require "prototypes.items.crops"
require "prototypes.items.machines"
require "prototypes.items.foods"
require "prototypes.items.materials"
require "prototypes.items.chemicals"
require "prototypes.items.environment-data"

require "prototypes.recipes.recipe-categories"
require "prototypes.recipes.machines"
require "prototypes.recipes.trading"
require "prototypes.recipes.cooking"
require "prototypes.recipes.process-crops"
require "prototypes.recipes.chemicals"
require "prototypes.recipes.materials"

require "prototypes.planet.controls"
require "prototypes.planet.planet"
-- require "prototypes.planet.noise-functions"