require "prototypes.utils"
require "prototypes.groups"
require "prototypes.buffs"
require "prototypes.technologies"
require "prototypes.projectiles"

require "prototypes.plants.plant-utils"
require "prototypes.plants.rockmalt"
require "prototypes.plants.redbloom"
require "prototypes.plants.nyxoleum"
require "prototypes.plants.mangroove"

require "prototypes.machines.oven"
require "prototypes.machines.research-center"
require "prototypes.machines.deep-fryer"
require "prototypes.machines.trader-t1"
require "prototypes.machines.living-inserter"
require "prototypes.machines.eternal-lantern"
require "prototypes.machines.windmill"
require "prototypes.machines.town-mortar-turret"
require "prototypes.machines.town-tesla-turret"
require "prototypes.machines.biolab"
require "prototypes.machines.basic-oven"

require "prototypes.items.crops"
require "prototypes.items.materials"
require "prototypes.items.fluids"
require "prototypes.items.foods"
require "prototypes.items.environment-data"
require "prototypes.items.microorganism"
require "prototypes.items.cultivations"

require "prototypes.recipes.recipe-categories"
require "prototypes.recipes.trading"
require "prototypes.recipes.cooking"
require "prototypes.recipes.process-crops"
require "prototypes.recipes.chemicals"
require "prototypes.recipes.materials"
require "prototypes.recipes.environment-data"
require "prototypes.recipes.giving"
require "prototypes.recipes.microorganism"
require "prototypes.recipes.husbandry"
require "prototypes.recipes.cultivations"
require "prototypes.recipes.butching"
require "prototypes.recipes.recycle" -- Must be last

require "prototypes.tiles.tile-utils"
require "prototypes.tiles.uniques"
require "prototypes.tiles.water"
require "prototypes.tiles.lowland"
require "prototypes.tiles.midland"
require "prototypes.tiles.highland"
require "prototypes.tiles.effects"

require "prototypes.noise-expressions.noise-utils"
require "prototypes.noise-expressions.aux-noise"
require "prototypes.noise-expressions.elevation"
require "prototypes.noise-expressions.temperature"
require "prototypes.noise-expressions.moisture"
require "prototypes.noise-expressions.rockpools"
require "prototypes.noise-expressions.plants"
require "prototypes.noise-expressions.starting"
require "prototypes.noise-expressions.decoratives"
require "prototypes.noise-expressions.tiles"
require "prototypes.noise-expressions.town"
require "prototypes.noise-expressions.entity-decoratives"
require "prototypes.noise-expressions.enemies"

require "prototypes.decorations.base-gleba"
require "prototypes.decorations.town"
require "prototypes.decorations.gleba-plants"

require "prototypes.enemies.pentapod"

require "prototypes.planet.controls"
require "prototypes.planet.planet"
require "prototypes.planet.connections"

require "prototypes.base-game-changes"