data:extend(
---@type data.ItemPrototype[]
  {
    {
      type = "item",
      name = "vangrove-fruit",
      icon = "__virentis__/graphics/icons/items/crops/vangrove-fruit.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "gnarpod-fruit",
      icon = "__virentis__/graphics/icons/items/crops/gnarpod-fruit.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "coneflora-pollen",
      icon = "__virentis__/graphics/icons/items/crops/coneflora-pollen.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "puffberry-fruit",
      icon = "__virentis__/graphics/icons/items/crops/puffberry-fruit.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "rockmalt-fruit",
      icon = "__virentis__/graphics/icons/items/crops/rockmalt-fruit.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "stone",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "rockmalt-bulb",
      icon = "__virentis__/graphics/icons/items/crops/rockmalt-bulb.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "rockmalt-scale",
      icon = "__virentis__/graphics/icons/items/crops/rockmalt-scale.png",
      subgroup = "virentis-crops",
      order = "a",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "grass",
      icon = "__virentis__/graphics/icons/items/crops/grass.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 30 * second,
      spoil_result = "spoilage",
      stack_size = 200,
      weight = 1 * kg,
    },
    {
      type = "item",
      name = "redbloom-fruit",
      icon = "__virentis__/graphics/icons/items/crops/redbloom-fruit.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
    },
  })
