data:extend(
---@type data.ItemPrototype[]
  {
    {
      type = "item",
      name = "rockmalt-fruit",
      icon = "__virentis-graphics__/icons/items/crops/rockmalt-fruit.png",
      subgroup = "virentis-crops",
      order = "ba",
      spoil_ticks = 30 * minute,
      spoil_result = "stone",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "rockmalt-bulb",
      icon = "__virentis-graphics__/icons/items/crops/rockmalt-bulb.png",
      subgroup = "virentis-crops",
      order = "bb",
      spoil_ticks = 10 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
      fuel_category = "chemical",
      fuel_value = "5MJ",
    },
    {
      type = "item",
      name = "rockmalt-scale",
      icon = "__virentis-graphics__/icons/items/crops/rockmalt-scale.png",
      subgroup = "virentis-crops",
      localised_name = { "item-name.rockmalt-scale" },
      order = "bc",
      stack_size = 50,
      weight = 5 * kg,
      plant_result = "rockmalt-tree",
      place_result = "rockmalt-tree",
    },
    {
      type = "item",
      name = "herb",
      icon = "__virentis-graphics__/icons/items/crops/herb.png",
      subgroup = "virentis-crops",
      order = "aa",
      spoil_ticks = 30 * minute,
      spoil_result = "spoilage",
      stack_size = 200,
      weight = 1 * kg,
    },
    {
      type = "item",
      name = "redbloom-fruit",
      icon = "__virentis-graphics__/icons/items/crops/redbloom-fruit.png",
      subgroup = "virentis-crops",
      localised_name = { "item-name.redbloom-fruit" },
      order = "ca",
      spoil_ticks = 30 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
      plant_result = "redbloom-tree",
      place_result= "redbloom-tree",
      fuel_category = "chemical",
      fuel_value = "5MJ",
    },
    {
      type = "item",
      name = "nyxoleum-sapling",
      icon = "__virentis-graphics__/icons/items/crops/nyxoleum-sapling.png",
      subgroup = "virentis-crops",
      localised_name = { "item-name.nyxoleum-sapling" },
      order = "ea",
      spoil_ticks = 30 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
      plant_result = "nyxoleum-tree",
      place_result = "nyxoleum-tree",
    },
    {
      type = "item",
      name = "nyxoleum-seed",
      icon = "__virentis-graphics__/icons/items/crops/nyxoleum-seed.png",
      subgroup = "virentis-crops",
      order = "eb",
      stack_size = 50,
      weight = 5 * kg,
      fuel_category = "chemical",
      fuel_value = "10MJ",
    },
    {
      type = "item",
      name = "mangroove-seed",
      icon = "__virentis-graphics__/icons/items/crops/mangroove-seed.png",
      subgroup = "virentis-crops",
      localised_name = { "item-name.mangroove-seed" },
      order = "da",
      stack_size = 50,
      weight = 5 * kg,
      plant_result = "mangroove-tree",
      place_result = "mangroove-tree",
    },
    {
      type = "item",
      name = "mangroove-fruit",
      pictures = {
        { filename = "__virentis-graphics__/icons/items/crops/mangroove-fruit-1.png", size = 64 , scale = 0.5 },
        { filename = "__virentis-graphics__/icons/items/crops/mangroove-fruit-2.png", size = 64 , scale = 0.5 }
      },
      icon = "__virentis-graphics__/icons/items/crops/mangroove-fruit-2.png",
      subgroup = "virentis-crops",
      order = "db",
      spoil_ticks = 30 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "living-wood",
      icon = "__virentis-graphics__/icons/items/crops/living-wood.png",
      subgroup = "virentis-crops",
      order = "dc",
      spoil_ticks = 20 * minute,
      spoil_result = "wood",
      stack_size = 50,
      weight = 5 * kg,
    },
  })
