data:extend(
---@type data.ItemPrototype[]
  {
    {
      type = "item",
      name = "rockmalt-fruit",
      icon = "__virentis__/graphics/icons/items/crops/rockmalt-fruit.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "stone",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "rockmalt-bulb",
      icon = "__virentis__/graphics/icons/items/crops/rockmalt-bulb.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "rockmalt-scale",
      icon = "__virentis__/graphics/icons/items/crops/rockmalt-scale.png",
      subgroup = "virentis-crops",
      order = "a",
      stack_size = 50,
      weight = 5 * kg,
      plant_result = "rockmalt-tree",
      place_result = "rockmalt-tree",
    },
    {
      type = "item",
      name = "grass",
      icon = "__virentis__/graphics/icons/items/crops/grass.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 1 * minute,
      spoil_result = "spoilage",
      stack_size = 200,
      weight = 1 * kg,
    },
    {
      type = "item",
      name = "redbloom-fruit",
      icon = "__virentis__/graphics/icons/items/crops/redbloom-fruit.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
      plant_result = "redbloom-tree",
      place_result = "redbloom-tree",
    },
    {
      type = "item",
      name = "nyxoleum-sapling",
      icon = "__virentis__/graphics/icons/items/crops/nyxoleum-sapling.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "nyxoleum-seed",
      icon = "__virentis__/graphics/icons/items/crops/nyxoleum-seed.png",
      subgroup = "virentis-crops",
      order = "a",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "mangroove-seed",
      icon = "__virentis__/graphics/icons/items/crops/mangroove-seed.png",
      subgroup = "virentis-crops",
      order = "a",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "mangroove-fruit",
      pictures = {
        { filename = "__virentis__/graphics/icons/items/crops/mangroove-fruit-1.png" },
        { filename = "__virentis__/graphics/icons/items/crops/mangroove-fruit-2.png" }
      },
      icon = "__virentis__/graphics/icons/items/crops/mangroove-fruit-2.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "spoilage",
      stack_size = 50,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "living-wood",
      icon = "__virentis__/graphics/icons/items/crops/living-wood.png",
      subgroup = "virentis-crops",
      order = "a",
      spoil_ticks = 5 * minute,
      spoil_result = "wood",
      stack_size = 50,
      weight = 5 * kg,
    },
  })
