data:extend(
  ---@type data.FluidPrototype[]
  {
    {
      type = "fluid",
      name = "vegetable-oil",
      icon = "__virentis-graphics__/icons/items/fluids/vegetable-oil.png",
      subgroup = "virentis-fluids",
      default_temperature = 25,
      base_color = {0.70, 0.50, 0.05},
      flow_color = {1, 0.85, 0.18},
      order = "aa",
    },
    {
      type = "fluid",
      name = "methanol",
      icon = "__virentis-graphics__/icons/items/fluids/methanol.png",
      subgroup = "virentis-fluids",
      default_temperature = 25,
      base_color = {0.3, 0.6, 0.9},
      flow_color = {0.6, 0.85, 1},
      order = "ab",
    },
    {
      type = "fluid",
      name = "tar",
      icon = "__virentis-graphics__/icons/items/fluids/tar.png",
      subgroup = "virentis-fluids",
      order = "ac",
      default_temperature = 25,
      base_color = {0.1, 0.1, 0.1},
      flow_color = {0.15, 0.15, 0.15},
    },
    {
      type = "fluid",
      name = "nutrients-pulp",
      icon = "__virentis-graphics__/icons/items/fluids/nutrients-pulp.png",
      subgroup = "virentis-fluids",
      order = "bb",
      default_temperature = 25,
      base_color = {0.70, 0.40, 0.15},
      flow_color = {0.85, 0.55, 0.28},
    },
    {
      type = "fluid",
      name = "fish-oil",
      icon = "__virentis-graphics__/icons/items/fluids/fish-oil.png",
      subgroup = "virentis-fluids",
      order = "ba",
      default_temperature = 25,
      base_color = {0.70, 0.40, 0.15},
      flow_color = {0.85, 0.55, 0.28},
    },
  }
)