data:extend(
---@type data.ItemPrototype[]
  {
    {
      type = "item",
      name = "resin",
      icon = "__virentis__/graphics/icons/items/materials/resin.png",
      subgroup = "virentis-materials",
      order = "a",
      stack_size = 200,
      weight = 5 * kg,
    },

    {
      type = "item",
      name = "heart-of-nature",
      icon = "__virentis__/graphics/icons/items/materials/heart-of-nature.png",
      subgroup = "virentis-materials",
      order = "a",
      stack_size = 50,
      weight = 20 * kg,
    },
    {
      type = "item",
      name = "siltcore",
      icon = "__virentis__/graphics/icons/items/materials/siltcore.png",
      subgroup = "virentis-materials",
      order = "a",
      stack_size = 50,
      weight = 20 * kg,
    },
    {
      type = "item",
      name = "firebrick",
      icon = "__virentis__/graphics/icons/items/materials/firebrick.png",
      subgroup = "virentis-materials",
      order = "a",
      stack_size = 200,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "phosphorus",
      icon = "__virentis__/graphics/icons/items/materials/phosphorus.png",
      subgroup = "virentis-materials",
      order = "a",
      stack_size = 200,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "creosote",
      icon = "__virentis__/graphics/icons/items/materials/creosote.png",
      subgroup = "virentis-materials",
      order = "a",
      stack_size = 200,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "nutrients-bar",
      icon = "__virentis__/graphics/icons/items/materials/nutrients-bar.png",
      subgroup = "virentis-materials",
      order = "a",
      stack_size = 200,
      weight = 5 * kg,
      fuel_category = "nutrients",
      fuel_value = "10MJ",
    },
  }
)
