data:extend(
---@type data.ItemPrototype[]
  {
    {
      type = "item",
      name = "resin",
      icon = "__virentis__/graphics/icons/items/materials/resin.png",
      subgroup = "virentis-materials",
      order = "ab",
      stack_size = 200,
      weight = 5 * kg,
    },

    {
      type = "item",
      name = "heart-of-nature",
      icon = "__virentis__/graphics/icons/items/materials/heart-of-nature.png",
      subgroup = "virentis-materials",
      order = "ad",
      stack_size = 50,
      weight = 20 * kg,
    },
    {
      type = "item",
      name = "siltcore",
      icon = "__virentis__/graphics/icons/items/materials/siltcore.png",
      subgroup = "virentis-materials",
      order = "ac",
      stack_size = 50,
      weight = 20 * kg,
    },
    {
      type = "item",
      name = "firebrick",
      icon = "__virentis__/graphics/icons/items/materials/firebrick.png",
      subgroup = "virentis-materials",
      order = "aa",
      stack_size = 200,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "phosphorus",
      icon = "__virentis__/graphics/icons/items/materials/phosphorus.png",
      subgroup = "virentis-materials",
      order = "ae",
      stack_size = 200,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "creosote",
      icon = "__virentis__/graphics/icons/items/materials/creosote.png",
      subgroup = "virentis-materials",
      order = "af",
      stack_size = 200,
      weight = 5 * kg,
    },
    {
      type = "item",
      name = "nutrients-bar",
      icon = "__virentis__/graphics/icons/items/materials/nutrients-bar.png",
      subgroup = "virentis-materials",
      order = "ah",
      stack_size = 200,
      spoil_result = "spoilage",
      spoil_ticks = 2 * minute,
      weight = 5 * kg,
      fuel_category = "nutrients",
      fuel_value = "10MJ",
    },
    {
      type = "item",
      name = "graphene",
      icon = "__virentis__/graphics/icons/items/materials/graphene.png",
      subgroup = "virentis-materials",
      order = "ag",
      stack_size = 200,
      weight = 5 * kg,
    },
  }
)
