-- Planet map generation settings
local asteroid_util = require("__space-age__.prototypes.planet.asteroid-spawn-definitions")
local planet_catalogue_gleba = require("__space-age__.prototypes.planet.procession-catalogue-gleba")

-- Create the actual planet prototype
data:extend({
  ---@type data.PlanetPrototype
  {
    type = "planet",
    name = "virentis",
    icon = "__virentis-graphics__/icons/misc/virentis-icon.png",
    icon_size = 256,
    pollutant_type = "spores",
    starmap_icon = "__virentis-graphics__/icons/misc/starmap-virentis.png",
    starmap_icon_size = 1080,
    gravity_pull = 10,
    distance = 25,
    orientation = 0.17,
    solar_power_in_space = 50,
    magnitude = 0.8,
    order = "ca",
    subgroup = "planets",
    platform_procession_set =
    {
      arrival = {"planet-to-platform-b"},
      departure = {"platform-to-planet-a"}
    },
    planet_procession_set =
    {
      arrival = {"platform-to-planet-b"},
      departure = {"planet-to-platform-a"}
    },
    procession_graphic_catalogue = planet_catalogue_gleba,
    persistent_ambient_sounds = table.deepcopy(data.raw["planet"]["gleba"].persistent_ambient_sounds),
    surface_render_parameters = table.deepcopy(data.raw["planet"]["gleba"].surface_render_parameters),
    map_gen_settings = {
      property_expression_names =
      {
        elevation = "virentis_elevation",
        temperature = "virentis_temperature",
        moisture = "virentis_moisture",
        aux = "virentis_aux",
        cliffiness = "virentis_cliffiness",
        cliff_elevation = "cliff_elevation_from_elevation",
        enemy_base_radius = "gleba_enemy_base_radius",
        enemy_base_frequency = "gleba_enemy_base_frequency",

        ["decorative:red-desert-bush:probability"] = "virentis_red_desert_bush_probability",
        ["decorative:white-desert-bush:probability"] = "virentis_white_desert_bush_probability",
        ["decorative:red-pita:probability"] = "virentis_red_pita_probability",
        ["decorative:green-bush-mini:probability"] = "virentis_green_bush_probability",
        ["decorative:green-croton:probability"] = "virentis_green_cronton_probability",
        ["decorative:green-pita:probability"] = "virentis_green_pita_probability",
        ["decorative:green-pita-mini:probability"] = "virentis_green_pita_mini_probability",
        ["decorative:lichen-decal:probability"] = "virentis_orange_lichen_probability",
        ["decorative:shroom-decal:probability"] = "virentis_carpet_shroom_probability",
        ["decorative:cracked-mud-decal:probability"] = "virentis_cracked_mud_probability",
        ["decorative:light-mud-decal:probability"] = "virentis_light_mud_probability",
        ["decorative:dark-mud-decal:probability"] = "virentis_dark_mud_probability",
        ["decorative:green-carpet-grass:probability"] = "virentis_green_carpet_grass_probability",
        ["decorative:green-hairy-grass:probability"] = "virentis_green_hairy_grass_probability",

        ["decorative:fulgoran-ruin-tiny:probability"] = "virentis_fulgoran_ruin_tiny_probability",
        ["decorative:fulgoran-gravewort:probability"] = "virentis_fulgoran_gravewort_probability",
        ["decorative:tiny-fulgora-rock:probability"] = "virentis_tiny_fulgora_rock_probability",
        ["decorative:small-fulgora-rock:probability"] = "virentis_small_fulgora_rock_probability",
        ["decorative:tiny-volcanic-rock:probability"] = "virentis_tiny_volcanic_rock_probability",
        ["decorative:small-volcanic-rock:probability"] = "virentis_small_volcanic_rock_probability",
        ["decorative:medium-volcanic-rock:probability"] = "virentis_medium_volcanic_rock_probability",
        ["decorative:crater-small:probability"] = "virentis_crater_small_probability",
        ["decorative:v-red-pita:probability"] = "virentis_vulcanus_pita_probability",

        ["entity:big-fulgora-rock:probability"] = "virentis_big_fulgora_rock_probability",

        ["entity:funneltrunk:probability"] = "virentis_funneltrunk_probability",
        ["entity:funneltrunk:control"] = "virentis_plants",
        ["entity:hairyclubnub:probability"] = "virentis_hairyclubnub_probability",
        ["entity:hairyclubnub:control"] = "virentis_plants",
        ["entity:teflilly:probability"] = "virentis_teflilly_probability",
        ["entity:teflilly:control"] = "virentis_plants",
        ["entity:lickmaw:probability"] = "virentis_lickmaw_probability",
        ["entity:lickmaw:control"] = "virentis_plants",
        ["entity:sunnycomb:probability"] = "virentis_sunnycomb_probability",
        ["entity:sunnycomb:control"] = "virentis_plants",
      },
      cliff_settings =
      {
        name = "cliff-gleba",
        control = "virentis_cliff",
        cliff_elevation_0 = 40,
        cliff_elevation_interval = 60,
        richness = 0.80,
        cliff_smoothing = 0 -- Not critical but looks better
      },
      autoplace_controls = {
        ["virentis_plants"] = {},
        ["virentis_water"] = {},
        ["virentis_cliff"] = {},
        ["virentis_town"] = {},
        ["virentis_enemy_base"] = {},
      },
      autoplace_settings = {
        ["tile"] = {
          settings = {
            ["mangroove-fertile-soil"] = {},
            ["rockmalt-fertile-soil"] = {},
            ["redbloom-fertile-soil"] = {},
            ["nyxoleum-fertile-soil"] = {},
            ["brineleaf-fertile-soil"] = {},
            ["tar-puddle"] = {},
            ["town-floor-edge"] = {},
            ["town-floor-center"] = {},
            ["virentis-deep-water"] = {},
            ["virentis-midland-cracked-lichen"] = {},
            ["virentis-midland-cracked-lichen-dull"] = {},
            ["virentis-midland-cracked-lichen-dark"] = {},
            ["virentis-midland-turquoise-bark-2"] = {},
            ["virentis-midland-turquoise-bark"] = {},
            ["virentis-midland-yellow-crust-3"] = {},
            ["virentis-midland-yellow-crust-2"] = {},
            ["virentis-midland-yellow-crust"] = {},
            ["virentis-midland-yellow-crust-4"] = {},
            ["virentis-highland-dark-rock"] = {},
            ["virentis-highland-dark-rock-2"] = {},
            ["virentis-highland-yellow-rock"] = {},
            ["virentis-lowland-olive-blubber"] = {},
            ["virentis-lowland-olive-blubber-2"] = {},
            ["virentis-lowland-olive-blubber-3"] = {},
            ["virentis-lowland-brown-blubber"] = {},
            ["virentis-lowland-pale-green"] = {},
            ["virentis-lowland-cream-cauliflower"] = {},
            ["virentis-lowland-cream-cauliflower-2"] = {},
            ["virentis-lowland-dead-skin"] = {},
            ["virentis-lowland-dead-skin-2"] = {},
            ["virentis-lowland-cream-red"] = {},
            ["virentis-lowland-red-vein"] = {},
            ["virentis-lowland-red-vein-2"] = {},
            ["virentis-lowland-red-vein-3"] = {},
            ["virentis-lowland-red-vein-4"] = {},
            ["virentis-lowland-red-vein-dead"] = {},
            ["virentis-lowland-red-infection"] = {},
            ["virentis-wetland-dead-skin"] = {},
            ["virentis-wetland-light-dead-skin"] = {},
            ["virentis-wetland-mud"] = {},
            ["virentis-wetland-mud-slime"] = {},
            ["virentis-wetland-light-mud-slime"] = {},
            ["virentis-wetland-red-tentacle"] = {},
            ["virentis-wetland-pink-tentacle"] = {},
            ["virentis-wetland-blue-slime"] = {},
          }
        },
        ["decorative"] = {
          settings = {
            ["virentis-yellow-lettuce-lichen-1x1"] = {},
            ["virentis-yellow-lettuce-lichen-3x3"] = {},
            ["virentis-yellow-lettuce-lichen-6x6"] = {},
            ["virentis-yellow-lettuce-lichen-cups-1x1"] = {},
            ["virentis-yellow-lettuce-lichen-cups-3x3"] = {},
            ["virentis-yellow-lettuce-lichen-cups-6x6"] = {},
            ["virentis-green-lettuce-lichen-1x1"] = {},
            ["virentis-green-lettuce-lichen-3x3"] = {},
            ["virentis-green-lettuce-lichen-6x6"] = {},
            ["virentis-green-lettuce-lichen-water-1x1"] = {},
            ["virentis-green-lettuce-lichen-water-3x3"] = {},
            ["virentis-green-lettuce-lichen-water-6x6"] = {},
            ["virentis-honeycomb-fungus"] = {},
            ["virentis-honeycomb-fungus-1x1"] = {},
            ["virentis-honeycomb-fungus-decayed"] = {},
            ["virentis-split-gill-1x1"] = {},
            ["virentis-split-gill-2x2"] = {},
            ["virentis-split-gill-dying-1x1"] = {},
            ["virentis-split-gill-dying-2x2"] = {},
            ["virentis-split-gill-red-1x1"] = {},
            ["virentis-split-gill-red-2x2"] = {},
            ["virentis-veins"] = {},
            ["virentis-veins-small"] = {},
            ["virentis-mycelium"] = {},
            ["virentis-coral-water"] = {},
            ["virentis-coral-land"] = {},
            ["virentis-black-sceptre"] = {},
            ["virentis-pink-phalanges"] = {},
            ["virentis-pink-lichen-decal"] = {},
            ["virentis-red-lichen-decal"] = {},
            ["virentis-green-cup"] = {},
            ["virentis-green-cup-brineleaf"] = {},
            ["virentis-brown-cup"] = {},
            ["virentis-blood-grape"] = {},
            ["virentis-blood-grape-vibrant"] = {},
            ["virentis-brambles"] = {},
            ["virentis-polycephalum-slime"] = {},
            ["virentis-polycephalum-balloon"] = {},
            ["virentis-fuchsia-pita"] = {},
            ["virentis-wispy-lichen"] = {},
            ["virentis-grey-cracked-mud-decal"] = {},
            ["virentis-barnacles-decal"] = {},
            ["virentis-coral-stunted"] = {},
            ["virentis-coral-stunted-grey"] = {},
            ["virentis-red-nerve-roots-veins-dense"] = {},
            ["virentis-red-nerve-roots-veins-sparse"] = {},
            ["virentis-purple-nerve-roots-veins-dense"] = {},
            ["virentis-purple-nerve-roots-veins-sparse"] = {},
            ["virentis-cream-nerve-roots-veins-dense"] = {},
            ["virentis-cream-nerve-roots-veins-sparse"] = {},
            ["virentis-yellow-coral"] = {},
            ["virentis-solo-barnacle"] = {},
            ["virentis-curly-roots-orange"] = {},
            ["virentis-knobbly-roots"] = {},
            ["virentis-knobbly-roots-orange"] = {},
            ["virentis-matches-small"] = {},
            ["virentis-pale-lettuce-lichen-cups-1x1"] = {},
            ["virentis-pale-lettuce-lichen-cups-3x3"] = {},
            ["virentis-pale-lettuce-lichen-cups-6x6"] = {},
            ["virentis-pale-lettuce-lichen-1x1"] = {},
            ["virentis-pale-lettuce-lichen-3x3"] = {},
            ["virentis-pale-lettuce-lichen-6x6"] = {},
            ["virentis-pale-lettuce-lichen-water-1x1"] = {},
            ["virentis-pale-lettuce-lichen-water-3x3"] = {},
            ["virentis-pale-lettuce-lichen-water-6x6"] = {},
            ["white-carpet-grass"] = {},
            ["green-carpet-grass"] = {},
            ["green-hairy-grass"] = {},

            --shared
            ["light-mud-decal"] = {},
            ["dark-mud-decal"] = {},
            ["cracked-mud-decal"] = {},
            ["red-desert-bush"] = {},
            ["white-desert-bush"] = {},
            ["red-pita"] = {},
            ["green-bush-mini"] = {},
            ["green-croton"] = {},
            ["green-pita"] = {},
            ["green-pita-mini"] = {},
            ["lichen-decal"] = {},
            ["shroom-decal"] = {},

            -- Town
            ["fulgoran-ruin-tiny"] = {},
            ["fulgoran-gravewort"] = {},
            ["tiny-fulgora-rock"] = {},
            ["small-fulgora-rock"] = {},

            -- Rockmalt
            ["tiny-volcanic-rock"] = {},
            ["small-volcanic-rock"] = {},
            ["medium-volcanic-rock"] = {},
            ["crater-small"] = {},
            ["v-red-pita"] = {},
          }
        },
        ["entity"] = {
          settings = {
            ["big-fulgora-rock"] = {},
            ["virentis-fulgoran-ruin-medium"] = {},
            ["virentis-fulgoran-ruin-stonehenge"] = {},
            ["town-mortar-turret"] = {},
            ["town-tesla-turret"] = {},
            ["trader-t1"] = {},
            ["eternal-lantern"] = {},
            ["windmill"] = {},
            ["funneltrunk"] = {},
            ["virentis-slipstack"] = {},
            ["hairyclubnub"] = {},
            ["teflilly"] = {},
            ["virentis-cuttlepop"] = {},
            ["lickmaw"] = {},
            ["sunnycomb"] = {},
            ["virentis-behemoth-stomper-shell"] = {},
            ["pentapus"] = {},
          }
        }
      }
    },
    surface_properties =
    {
      ["day-night-cycle"] = 5 * minute,
      ["magnetic-field"] = 25,
      ["solar-power"] = 10,
      pressure = 1200,
      gravity = 10
    },
    -- Using default surface render parameters
    asteroid_spawn_influence = 1,
    asteroid_spawn_definitions = asteroid_util.spawn_definitions(asteroid_util.gleba_fulgora, 0.9)
  }
})
